version: '3.8'

services:
  app:
    container_name: "tour-guide-suggestion-frontend"
    networks:
      - server
    ports:
      - 5800:4800
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
networks:
  server:
    external: true
